//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.2
//     from Assets/+++Workdata/Input/InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActions"",
    ""maps"": [
        {
            ""name"": ""PlayerKeyboardMouseActionMap"",
            ""id"": ""3b22308c-1ae7-4663-9691-23aa1a9cabbc"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""27fa00c0-9146-4a8c-837e-89e4a8796062"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""f6070509-73e0-4816-89c3-aecdc9e99f65"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Ultimate"",
                    ""type"": ""Button"",
                    ""id"": ""682bf956-d287-4d70-a51f-7225552ced05"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""869709af-5c52-474b-b3f3-b6a19a014154"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""6cf07c57-eb05-444e-87a7-193c0abadb4e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwapWeapon"",
                    ""type"": ""Button"",
                    ""id"": ""613147af-5da8-4095-b432-fa1ca46d413a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenInventory"",
                    ""type"": ""Button"",
                    ""id"": ""041a2f66-08f8-4f78-bb3e-0a9e6106116c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseFlask"",
                    ""type"": ""Button"",
                    ""id"": ""8e0b1669-dd9e-4f6e-9352-3c7837b2b122"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""60ab1a31-5445-4553-b6c3-8fa33f5f2760"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""2651d5b6-9929-446e-86ff-7929b0af232b"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""ade3992e-0700-41f7-9dc2-8ca7cf10451d"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""14ec918e-d250-45b1-adb7-07a67e0d206b"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""58461251-3bec-4ab8-8c69-636607535487"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""e17238ef-d34e-4ae9-b286-93d4f8bd155c"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""24d94156-be21-4cf7-a630-a8565c53d0dd"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e4585046-a135-411f-b626-01f25db844cc"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwapWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""004a4e92-4832-4f95-89cc-00b9144c9ac0"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f337afef-9b9b-41ad-a677-0c00da3699c0"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4c4f0fed-3f10-4ba8-8699-8ef2aa895eaf"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ultimate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8467dc6a-1ef2-4afe-b618-4ae62c75bf7f"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseFlask"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PlayerControllerActionMap"",
            ""id"": ""5831195e-10a6-4774-8c6e-72c0629a1947"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""278c7717-edb4-4a12-a7a6-231f082a15f9"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""48508fcc-f954-483a-993f-b6265cae38cf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""97bb2498-77c9-4798-9da3-ecc00bed1fae"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Ultimate"",
                    ""type"": ""Button"",
                    ""id"": ""a1063420-f10d-42b0-b5e2-7504586ab7bd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""00707ded-db4c-42cb-8fba-64e205278442"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwapWeapon"",
                    ""type"": ""Button"",
                    ""id"": ""691d4cc3-b084-499c-9822-0b14e2656229"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenInventory"",
                    ""type"": ""Button"",
                    ""id"": ""c4669f3d-f35f-4542-bda8-dd43362305c3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseFlask"",
                    ""type"": ""Button"",
                    ""id"": ""fd63564f-cdb1-43f9-9256-e573d2cc669c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""fbb60921-a5fa-4e68-a715-d73390a18e11"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""c14bd7b0-1294-4bde-9328-40cb3bd175bc"",
                    ""path"": ""<XInputController>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""545f9faa-bf17-4c6d-9b81-1c988cca5e5d"",
                    ""path"": ""<XInputController>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""4cd1d847-208f-4e43-908f-a358c89ebe4a"",
                    ""path"": ""<XInputController>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""3d009586-3a6a-4c93-864f-7a72aa1531cd"",
                    ""path"": ""<XInputController>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""3f69355f-975b-478e-8466-875b8172f041"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e25f47b8-b7f5-422a-bea0-c8ed68116503"",
                    ""path"": ""<XInputController>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9a7f99dd-643b-4028-aefe-d8aa9c7b851e"",
                    ""path"": ""<XInputController>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwapWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""912fccdb-f147-48e8-a52c-fb520e275bfd"",
                    ""path"": ""<XInputController>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""67569f4e-d5fc-4ee6-b61a-899e108d5fb3"",
                    ""path"": ""<XInputController>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bd41180c-bb37-4c8e-9bc7-a3a54c6bbcf9"",
                    ""path"": ""<XInputController>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ultimate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2616fee0-ba88-4155-812b-4f2e787dbc75"",
                    ""path"": ""<XInputController>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseFlask"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerKeyboardMouseActionMap
        m_PlayerKeyboardMouseActionMap = asset.FindActionMap("PlayerKeyboardMouseActionMap", throwIfNotFound: true);
        m_PlayerKeyboardMouseActionMap_Movement = m_PlayerKeyboardMouseActionMap.FindAction("Movement", throwIfNotFound: true);
        m_PlayerKeyboardMouseActionMap_Interact = m_PlayerKeyboardMouseActionMap.FindAction("Interact", throwIfNotFound: true);
        m_PlayerKeyboardMouseActionMap_Ultimate = m_PlayerKeyboardMouseActionMap.FindAction("Ultimate", throwIfNotFound: true);
        m_PlayerKeyboardMouseActionMap_Attack = m_PlayerKeyboardMouseActionMap.FindAction("Attack", throwIfNotFound: true);
        m_PlayerKeyboardMouseActionMap_Dash = m_PlayerKeyboardMouseActionMap.FindAction("Dash", throwIfNotFound: true);
        m_PlayerKeyboardMouseActionMap_SwapWeapon = m_PlayerKeyboardMouseActionMap.FindAction("SwapWeapon", throwIfNotFound: true);
        m_PlayerKeyboardMouseActionMap_OpenInventory = m_PlayerKeyboardMouseActionMap.FindAction("OpenInventory", throwIfNotFound: true);
        m_PlayerKeyboardMouseActionMap_UseFlask = m_PlayerKeyboardMouseActionMap.FindAction("UseFlask", throwIfNotFound: true);
        // PlayerControllerActionMap
        m_PlayerControllerActionMap = asset.FindActionMap("PlayerControllerActionMap", throwIfNotFound: true);
        m_PlayerControllerActionMap_Movement = m_PlayerControllerActionMap.FindAction("Movement", throwIfNotFound: true);
        m_PlayerControllerActionMap_Interact = m_PlayerControllerActionMap.FindAction("Interact", throwIfNotFound: true);
        m_PlayerControllerActionMap_Attack = m_PlayerControllerActionMap.FindAction("Attack", throwIfNotFound: true);
        m_PlayerControllerActionMap_Ultimate = m_PlayerControllerActionMap.FindAction("Ultimate", throwIfNotFound: true);
        m_PlayerControllerActionMap_Dash = m_PlayerControllerActionMap.FindAction("Dash", throwIfNotFound: true);
        m_PlayerControllerActionMap_SwapWeapon = m_PlayerControllerActionMap.FindAction("SwapWeapon", throwIfNotFound: true);
        m_PlayerControllerActionMap_OpenInventory = m_PlayerControllerActionMap.FindAction("OpenInventory", throwIfNotFound: true);
        m_PlayerControllerActionMap_UseFlask = m_PlayerControllerActionMap.FindAction("UseFlask", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerKeyboardMouseActionMap
    private readonly InputActionMap m_PlayerKeyboardMouseActionMap;
    private IPlayerKeyboardMouseActionMapActions m_PlayerKeyboardMouseActionMapActionsCallbackInterface;
    private readonly InputAction m_PlayerKeyboardMouseActionMap_Movement;
    private readonly InputAction m_PlayerKeyboardMouseActionMap_Interact;
    private readonly InputAction m_PlayerKeyboardMouseActionMap_Ultimate;
    private readonly InputAction m_PlayerKeyboardMouseActionMap_Attack;
    private readonly InputAction m_PlayerKeyboardMouseActionMap_Dash;
    private readonly InputAction m_PlayerKeyboardMouseActionMap_SwapWeapon;
    private readonly InputAction m_PlayerKeyboardMouseActionMap_OpenInventory;
    private readonly InputAction m_PlayerKeyboardMouseActionMap_UseFlask;
    public struct PlayerKeyboardMouseActionMapActions
    {
        private @InputActions m_Wrapper;
        public PlayerKeyboardMouseActionMapActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_PlayerKeyboardMouseActionMap_Movement;
        public InputAction @Interact => m_Wrapper.m_PlayerKeyboardMouseActionMap_Interact;
        public InputAction @Ultimate => m_Wrapper.m_PlayerKeyboardMouseActionMap_Ultimate;
        public InputAction @Attack => m_Wrapper.m_PlayerKeyboardMouseActionMap_Attack;
        public InputAction @Dash => m_Wrapper.m_PlayerKeyboardMouseActionMap_Dash;
        public InputAction @SwapWeapon => m_Wrapper.m_PlayerKeyboardMouseActionMap_SwapWeapon;
        public InputAction @OpenInventory => m_Wrapper.m_PlayerKeyboardMouseActionMap_OpenInventory;
        public InputAction @UseFlask => m_Wrapper.m_PlayerKeyboardMouseActionMap_UseFlask;
        public InputActionMap Get() { return m_Wrapper.m_PlayerKeyboardMouseActionMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerKeyboardMouseActionMapActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerKeyboardMouseActionMapActions instance)
        {
            if (m_Wrapper.m_PlayerKeyboardMouseActionMapActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_PlayerKeyboardMouseActionMapActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_PlayerKeyboardMouseActionMapActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_PlayerKeyboardMouseActionMapActionsCallbackInterface.OnMovement;
                @Interact.started -= m_Wrapper.m_PlayerKeyboardMouseActionMapActionsCallbackInterface.OnInteract;
                @Interact.performed -= m_Wrapper.m_PlayerKeyboardMouseActionMapActionsCallbackInterface.OnInteract;
                @Interact.canceled -= m_Wrapper.m_PlayerKeyboardMouseActionMapActionsCallbackInterface.OnInteract;
                @Ultimate.started -= m_Wrapper.m_PlayerKeyboardMouseActionMapActionsCallbackInterface.OnUltimate;
                @Ultimate.performed -= m_Wrapper.m_PlayerKeyboardMouseActionMapActionsCallbackInterface.OnUltimate;
                @Ultimate.canceled -= m_Wrapper.m_PlayerKeyboardMouseActionMapActionsCallbackInterface.OnUltimate;
                @Attack.started -= m_Wrapper.m_PlayerKeyboardMouseActionMapActionsCallbackInterface.OnAttack;
                @Attack.performed -= m_Wrapper.m_PlayerKeyboardMouseActionMapActionsCallbackInterface.OnAttack;
                @Attack.canceled -= m_Wrapper.m_PlayerKeyboardMouseActionMapActionsCallbackInterface.OnAttack;
                @Dash.started -= m_Wrapper.m_PlayerKeyboardMouseActionMapActionsCallbackInterface.OnDash;
                @Dash.performed -= m_Wrapper.m_PlayerKeyboardMouseActionMapActionsCallbackInterface.OnDash;
                @Dash.canceled -= m_Wrapper.m_PlayerKeyboardMouseActionMapActionsCallbackInterface.OnDash;
                @SwapWeapon.started -= m_Wrapper.m_PlayerKeyboardMouseActionMapActionsCallbackInterface.OnSwapWeapon;
                @SwapWeapon.performed -= m_Wrapper.m_PlayerKeyboardMouseActionMapActionsCallbackInterface.OnSwapWeapon;
                @SwapWeapon.canceled -= m_Wrapper.m_PlayerKeyboardMouseActionMapActionsCallbackInterface.OnSwapWeapon;
                @OpenInventory.started -= m_Wrapper.m_PlayerKeyboardMouseActionMapActionsCallbackInterface.OnOpenInventory;
                @OpenInventory.performed -= m_Wrapper.m_PlayerKeyboardMouseActionMapActionsCallbackInterface.OnOpenInventory;
                @OpenInventory.canceled -= m_Wrapper.m_PlayerKeyboardMouseActionMapActionsCallbackInterface.OnOpenInventory;
                @UseFlask.started -= m_Wrapper.m_PlayerKeyboardMouseActionMapActionsCallbackInterface.OnUseFlask;
                @UseFlask.performed -= m_Wrapper.m_PlayerKeyboardMouseActionMapActionsCallbackInterface.OnUseFlask;
                @UseFlask.canceled -= m_Wrapper.m_PlayerKeyboardMouseActionMapActionsCallbackInterface.OnUseFlask;
            }
            m_Wrapper.m_PlayerKeyboardMouseActionMapActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @Interact.started += instance.OnInteract;
                @Interact.performed += instance.OnInteract;
                @Interact.canceled += instance.OnInteract;
                @Ultimate.started += instance.OnUltimate;
                @Ultimate.performed += instance.OnUltimate;
                @Ultimate.canceled += instance.OnUltimate;
                @Attack.started += instance.OnAttack;
                @Attack.performed += instance.OnAttack;
                @Attack.canceled += instance.OnAttack;
                @Dash.started += instance.OnDash;
                @Dash.performed += instance.OnDash;
                @Dash.canceled += instance.OnDash;
                @SwapWeapon.started += instance.OnSwapWeapon;
                @SwapWeapon.performed += instance.OnSwapWeapon;
                @SwapWeapon.canceled += instance.OnSwapWeapon;
                @OpenInventory.started += instance.OnOpenInventory;
                @OpenInventory.performed += instance.OnOpenInventory;
                @OpenInventory.canceled += instance.OnOpenInventory;
                @UseFlask.started += instance.OnUseFlask;
                @UseFlask.performed += instance.OnUseFlask;
                @UseFlask.canceled += instance.OnUseFlask;
            }
        }
    }
    public PlayerKeyboardMouseActionMapActions @PlayerKeyboardMouseActionMap => new PlayerKeyboardMouseActionMapActions(this);

    // PlayerControllerActionMap
    private readonly InputActionMap m_PlayerControllerActionMap;
    private IPlayerControllerActionMapActions m_PlayerControllerActionMapActionsCallbackInterface;
    private readonly InputAction m_PlayerControllerActionMap_Movement;
    private readonly InputAction m_PlayerControllerActionMap_Interact;
    private readonly InputAction m_PlayerControllerActionMap_Attack;
    private readonly InputAction m_PlayerControllerActionMap_Ultimate;
    private readonly InputAction m_PlayerControllerActionMap_Dash;
    private readonly InputAction m_PlayerControllerActionMap_SwapWeapon;
    private readonly InputAction m_PlayerControllerActionMap_OpenInventory;
    private readonly InputAction m_PlayerControllerActionMap_UseFlask;
    public struct PlayerControllerActionMapActions
    {
        private @InputActions m_Wrapper;
        public PlayerControllerActionMapActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_PlayerControllerActionMap_Movement;
        public InputAction @Interact => m_Wrapper.m_PlayerControllerActionMap_Interact;
        public InputAction @Attack => m_Wrapper.m_PlayerControllerActionMap_Attack;
        public InputAction @Ultimate => m_Wrapper.m_PlayerControllerActionMap_Ultimate;
        public InputAction @Dash => m_Wrapper.m_PlayerControllerActionMap_Dash;
        public InputAction @SwapWeapon => m_Wrapper.m_PlayerControllerActionMap_SwapWeapon;
        public InputAction @OpenInventory => m_Wrapper.m_PlayerControllerActionMap_OpenInventory;
        public InputAction @UseFlask => m_Wrapper.m_PlayerControllerActionMap_UseFlask;
        public InputActionMap Get() { return m_Wrapper.m_PlayerControllerActionMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerControllerActionMapActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerControllerActionMapActions instance)
        {
            if (m_Wrapper.m_PlayerControllerActionMapActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_PlayerControllerActionMapActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_PlayerControllerActionMapActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_PlayerControllerActionMapActionsCallbackInterface.OnMovement;
                @Interact.started -= m_Wrapper.m_PlayerControllerActionMapActionsCallbackInterface.OnInteract;
                @Interact.performed -= m_Wrapper.m_PlayerControllerActionMapActionsCallbackInterface.OnInteract;
                @Interact.canceled -= m_Wrapper.m_PlayerControllerActionMapActionsCallbackInterface.OnInteract;
                @Attack.started -= m_Wrapper.m_PlayerControllerActionMapActionsCallbackInterface.OnAttack;
                @Attack.performed -= m_Wrapper.m_PlayerControllerActionMapActionsCallbackInterface.OnAttack;
                @Attack.canceled -= m_Wrapper.m_PlayerControllerActionMapActionsCallbackInterface.OnAttack;
                @Ultimate.started -= m_Wrapper.m_PlayerControllerActionMapActionsCallbackInterface.OnUltimate;
                @Ultimate.performed -= m_Wrapper.m_PlayerControllerActionMapActionsCallbackInterface.OnUltimate;
                @Ultimate.canceled -= m_Wrapper.m_PlayerControllerActionMapActionsCallbackInterface.OnUltimate;
                @Dash.started -= m_Wrapper.m_PlayerControllerActionMapActionsCallbackInterface.OnDash;
                @Dash.performed -= m_Wrapper.m_PlayerControllerActionMapActionsCallbackInterface.OnDash;
                @Dash.canceled -= m_Wrapper.m_PlayerControllerActionMapActionsCallbackInterface.OnDash;
                @SwapWeapon.started -= m_Wrapper.m_PlayerControllerActionMapActionsCallbackInterface.OnSwapWeapon;
                @SwapWeapon.performed -= m_Wrapper.m_PlayerControllerActionMapActionsCallbackInterface.OnSwapWeapon;
                @SwapWeapon.canceled -= m_Wrapper.m_PlayerControllerActionMapActionsCallbackInterface.OnSwapWeapon;
                @OpenInventory.started -= m_Wrapper.m_PlayerControllerActionMapActionsCallbackInterface.OnOpenInventory;
                @OpenInventory.performed -= m_Wrapper.m_PlayerControllerActionMapActionsCallbackInterface.OnOpenInventory;
                @OpenInventory.canceled -= m_Wrapper.m_PlayerControllerActionMapActionsCallbackInterface.OnOpenInventory;
                @UseFlask.started -= m_Wrapper.m_PlayerControllerActionMapActionsCallbackInterface.OnUseFlask;
                @UseFlask.performed -= m_Wrapper.m_PlayerControllerActionMapActionsCallbackInterface.OnUseFlask;
                @UseFlask.canceled -= m_Wrapper.m_PlayerControllerActionMapActionsCallbackInterface.OnUseFlask;
            }
            m_Wrapper.m_PlayerControllerActionMapActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @Interact.started += instance.OnInteract;
                @Interact.performed += instance.OnInteract;
                @Interact.canceled += instance.OnInteract;
                @Attack.started += instance.OnAttack;
                @Attack.performed += instance.OnAttack;
                @Attack.canceled += instance.OnAttack;
                @Ultimate.started += instance.OnUltimate;
                @Ultimate.performed += instance.OnUltimate;
                @Ultimate.canceled += instance.OnUltimate;
                @Dash.started += instance.OnDash;
                @Dash.performed += instance.OnDash;
                @Dash.canceled += instance.OnDash;
                @SwapWeapon.started += instance.OnSwapWeapon;
                @SwapWeapon.performed += instance.OnSwapWeapon;
                @SwapWeapon.canceled += instance.OnSwapWeapon;
                @OpenInventory.started += instance.OnOpenInventory;
                @OpenInventory.performed += instance.OnOpenInventory;
                @OpenInventory.canceled += instance.OnOpenInventory;
                @UseFlask.started += instance.OnUseFlask;
                @UseFlask.performed += instance.OnUseFlask;
                @UseFlask.canceled += instance.OnUseFlask;
            }
        }
    }
    public PlayerControllerActionMapActions @PlayerControllerActionMap => new PlayerControllerActionMapActions(this);
    public interface IPlayerKeyboardMouseActionMapActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnUltimate(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
        void OnSwapWeapon(InputAction.CallbackContext context);
        void OnOpenInventory(InputAction.CallbackContext context);
        void OnUseFlask(InputAction.CallbackContext context);
    }
    public interface IPlayerControllerActionMapActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
        void OnUltimate(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
        void OnSwapWeapon(InputAction.CallbackContext context);
        void OnOpenInventory(InputAction.CallbackContext context);
        void OnUseFlask(InputAction.CallbackContext context);
    }
}
